# Generated by Django 5.2.17 on 2026-09-21 09:47

import apps.asset.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature_tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.ImageField(upload_to=apps.asset.models.asset_upload_path)),
                ('frame_width', models.PositiveIntegerField(default=32, help_text='Width of a single animation frame, in pixels.')),
                ('frame_height', models.PositiveIntegerField(default=32, help_text='Height of a single animation frame, in pixels.')),
                ('license_type', models.CharField(choices=[('cc0', 'CC0 - Public Domain'), ('cc-by', 'CC BY - Attribution'), ('cc-by-sa', 'CC BY-SA - Attribution-ShareAlike'), ('all-rights-reserved', 'All Rights Reserved'), ('custom', 'Custom / Other')], default='all-rights-reserved', max_length=50)),
                ('file_size_kb', models.PositiveIntegerField(default=0, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_asset.asset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_tag.tag')),
            ],
            options={
                'unique_together': {('asset', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', through='feature_asset.AssetTag', to='feature_tag.tag'),
        ),
    ]
