# Generated by Django 5.2.17 on 2026-09-21 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature_asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShelfAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_asset.asset')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_shelf.shelf')),
            ],
            options={
                'unique_together': {('shelf', 'asset')},
            },
        ),
        migrations.AddField(
            model_name='shelf',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='shelves', through='feature_shelf.ShelfAsset', to='feature_asset.asset'),
        ),
    ]
